name: Build and Push to ECR

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - service: backend
            ecr_secret: ECR_REPOSITORY_BACKEND
          - service: frontend
            ecr_secret: ECR_REPOSITORY_FRONTEND

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag and push ${{ matrix.service }}
        env:
          ECR_REGISTRY:   ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG:      latest
          ECR_REPOSITORY: ${{ secrets[matrix.ecr_secret] }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./${{ matrix.service }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG