strategy:
  matrix:
    include:
      - service: backend
        ecr_repository: backend
      - service: frontend
        ecr_repository: frontend

steps:
  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v1

  - name: Build, tag and push ${{ matrix.service }}
    env:
      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      IMAGE_TAG: latest
      ECR_REPOSITORY: ${{ matrix.ecr_repository }}
    run: |
      echo "Building image $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
      docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./${{ matrix.service }}
      docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
